### ISSUE TITLE
Data file update has no response

### ISSUE THREAD

**Issue by pmarcis** [hltfbk/MT-EQuAl#3]
I tried uploading some files (in the correct format), but the system just reloads the page - nothing happens. There is also no error message.

**Comment by pmarcis** [comment]
Found the issue - the _root_ user does not have the rights to upload data.

I added a check for `|| $mysession["status"] == "root"` in the _add new sentence_ section and it works now.

**Comment by cgirardi** [comment]
The best is to permit the access to "root" and to leave out it from "advisor" (advisor user can not change the data). So I fixed the bug changing the line from:
if (!empty($mysession["status"]) && ($mysession["status"] == "admin" || $mysession["status"] == "advisor")) {

to:
if (!empty($mysession["status"]) && ($mysession["status"] == "admin" || $mysession["status"] == "root")) {

Thanks for your feedbacks!
